name: basketapp
#name: Gomudi
description: A mobile application for grocery shop

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  loader_search_bar:
  cupertino_icons:
  flutter_range_slider:
  carousel_pro:
  firebase_auth:
  cloud_firestore:
  flutter_mobx:
  mobx:
  provider:
  mobx_codegen:
  firebase_storage:
  cached_network_image:
  image_picker:
  font_awesome_flutter:
  rflutter_alert:
  google_fonts:
  pdf:
  path_provider:
  flutter_full_pdf_viewer:
  badges:
  syncfusion_flutter_pdf:
  open_file:
  geolocator:
  flappy_search_bar:
  flutter_facebook_login:
  google_sign_in:
  awesome_dialog:
  translator:
  scratcher:
  animated_text_kit:
  flutter_mailer: ^0.4.1+1
  mailer2:
  mailer:
  intl:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter


  build_runner:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  image_path: 'images/gomudilogo.png'
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - images/back.jpg
    - images/groceries.jpg
    - images/grtwo.jpg
    - images/grthre.jpg
    - images/veg.jpg
    - images/frozen.jpg
    - images/bev.jpg
    - images/brand_f.jpg
    - images/be.jpg
    - images/eggs.jpg
    - images/home.jpg
    - images/nonveg.jpg
    - images/apple.jpg
    - images/grapes.jpg
    - images/guava.jpg
    - images/kiwi.jpg
    - images/lemons.jpg
    - images/pineapple.jpg
    - images/tomato.jpg
    - images/gro_TEST.jpg
    - images/logo.png
    - images/masala4.jpeg
    - images/masala3.jpeg
    - images/groceries.jpg
    - images/brandlogo.png
    - images/spices.jpg
    - images/masala.jpg
    - images/google.jpg
    - images/facebook.jpg
    - images/gomudilogo.png
    - images/noitemimage.png
    - images/no-image.png
    - images/noprofileimage.png
    - images/diamond_bw.png







  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
